[package]
name = "aoc-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"

itertools = "0.10.1"

log = "0.4.14"
log-derive = "0.4.1"
simple_logger = "1.15.0"